# Generated by Django 5.0.6 on 2024-05-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_old",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="item",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
